on:
  # Triggers the workflow every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}  
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
      
      # add software dependencies here
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("slackr", "dplyr", "tidyr", "lubridate", "purrr", "reactable"))'

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
